### ISSUE TITLE
Boomfly leads to camera jumping for spectators

### ISSUE THREAD

**Issue by bretonium** [infclass/infclass-client#17]
Steps to reproduce:

1. 4 players: 1 spectator, 1 human, 1 boomer, 1 zombie
2. Spectator spectates any point of the map
3. Boomer boomflies a zombie

Expected: spectator's camera stays where the spectator left it, or on the player the spectator chose
Observed: spectator's camera jumps to the place of boomfly, or follows the player that has been boomflied. This happens even when the camera focuses on a specific player.

I am not sure whether the issue happens only on infclass-client-aware servers or on all servers.

Server-side bugreport: https://github.com/InfectionDust/teeworlds-infclassR/issues/70

**Comment by Kaffeine** [comment]
Fixed on the server side (https://github.com/InfectionDust/teeworlds-infclassR/issues/70 / https://github.com/InfectionDust/teeworlds-infclassR/commit/aea4e31c6b2a520bd20f2324ae633c45ed90b228)
