### ISSUE TITLE
Personal binds should not be overriden

### ISSUE THREAD

**Issue by bretonium** [infclass/infclass-client#22]
I use W for jumping and AD for moving left-right. Client version ce3fc47a5 overrode my preference, making it absolutely impossible to move around. Other personal binds should not be changed too - i use `z` to call the witch for the last few years, and want it to remain this way.

**Comment by Kaffeine** [comment]
Easy.
![image](https://user-images.githubusercontent.com/374839/153722334-eaf6ffeb-f9a1-4f53-8126-9104cef77d36.png)

**Comment by Kaffeine** [comment]
The infc bindings now [disabled](https://github.com/infclass/infclass-client/commit/ee3b92f917eda097c5e48b47059bf62b72446def) by default.
But if you've run the version with bindings enabled by default then you still have to manually click on the `Unbind` button on this settings page (or drop `settings_infclass.cfg` in the config directory).
